name: Deploy Chain

on:
  workflow_dispatch:
    inputs:
      CHAIN_NAME:
        description: 'Chain Name (kebab-case)'
        required: true
      RPC_URL:
        description: 'RPC URL'
        required: true
      PK:
        description: 'Private Key (0x...)'
        required: false  
      PROD:
        type: boolean
        description: 'Is this a production deployment?'
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build project
        working-directory: apps/firebase
        run: yarn build

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ github.event.inputs.PROD == 'true' && projects/1094498259535/locations/global/workloadIdentityPools/gh-faucet-master/providers/github-by-repos || projects/1094498259535/locations/global/workloadIdentityPools/gh-faucet/providers/github-by-repos }}
          service_account: ${{ github.event.inputs.PROD == 'true' && 'faucet-deploy-firebase@celo-faucet.iam.gserviceaccount.com' || 'faucet-deploy-firebase-staging@celo-faucet-staging.iam.gserviceaccount.com' }}
 
      - name: Set PK
        if: ${{ github.event.inputs.PK != '' }}
        run: |
          yarn firebase use ${{github.event.inputs.PROD == 'true' && 'celo-faucet' || 'celo-faucet-staging'}}
          yarn cli accounts:add  ${{ github.event.inputs.PK }} --net ${{ github.event.inputs.CHAIN_NAME }}
      - name: Set Firebase project and Deploy Firebase Function
        working-directory: apps/firebase
        run: |
          yarn firebase use ${{ github.event.inputs.PROD == 'true' && 'celo-faucet' || 'celo-faucet-staging' }}
          yarn cli config:set --net ${{ github.event.inputs.CHAIN_NAME }} --nodeUrl="${{ github.event.inputs.RPC_URL }}" --faucetGoldAmount 300000000000000000 --authenticatedGoldAmount 3000000000000000000
          yarn firebase deploy --only functions:faucetRequestProcessor
      
